### ISSUE TITLE
improve the example in the Readme

### ISSUE THREAD

**Issue by minimaldesign** [postcss/postcss-calc#106]
Maybe I'm misunderstanding what this plugin does? I'm trying to use it in Gatsby:

```js
postCssPlugins: [
  require(`postcss-preset-env`)({ browsers: "last 2 versions" }),
  require(`postcss-calc`)(),
],
```
in my CSS I got something like that:

```css
:root {
  --space-base: 16px;
  --space-xs: calc(var(--space-base) * 0.25);
  --test: calc(16px * 0.25);
  /* etc... */
```

And this is the output:
```css
:root {
  --space-xs: calc(var(--space-base)*0.25);
  --test: 4px;
```

I would have assumed both would be equal to `4px` (that's why I'm using this plugin in the first place). Is this a bug or I'm just not using this right?

Thanks!

**Comment by evilebottnawi** [comment]
It is expected, because CSS variables are hoisted and we can't inline them values, you can create postcss plugin for this, but it is unsafe, you can define CSS variables in other files/in HTML using `style`/using JS and etc, also `--space-base` can be calc too

**Comment by crabkiller** [comment]
> It is expected, because CSS variables are hoisted and we can't inline them values, you can create postcss plugin for this, but it is unsafe, you can define CSS variables in other files/in HTML using `style`/using JS and etc, also `--space-base` can be calc too

![image](https://user-images.githubusercontent.com/4629430/96683839-4605fe80-13ad-11eb-90ff-4587f5bfccbc.png)
I think this may be wrong as `README.md` example shows here.

**Comment by ludofischer** [comment]
I think the README example is confusing as it uses the [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) to replace the variables. postcss-calc alone will not do it.
