### ISSUE TITLE
Direct CSS input

### ISSUE THREAD

**Issue by drolsen** [postcss/postcss-calc#118]
Using this plugin as a process chain in POSTCSS configuration is great, however would be even better to be able to pass the plugin some CSS (decl preferable) to parse / reduce as well.

We are building a few internal plugins / methods that allow calc() usage, but would require special handling and being able to parse specifics.

Thanks!

**Comment by Semigradsky** [comment]
This plugin has used https://github.com/MoOx/reduce-css-calc before, you can try it.

**Comment by ludofischer** [comment]
I think standalone usage is out of scope, but the project linked in the previous comment does seem to work as a substitute.
