### ISSUE TITLE
Simple var multiplication breaks

### ISSUE THREAD

**Issue by ThornWalli** [postcss/postcss-calc#124]
Have a problem with the current version `7.0.5`

This calc can not be solved anymore:

`left: calc(-2 * var(--gutter-width));`

No problems with version `7.0.4`.

`--gutter-width` is `15px`

**Comment by csr632** [comment]
How could `calc(-2 * var(--gutter-width))` be further simplified by postcss-calc ?  It can't know how much is `var(--gutter-width)` at the build time!

> No problems with version 7.0.4.
What is the behaviour of 7.0.4?

**Comment by saschaeggi** [comment]
Having the same problem with 7.0.5

**Comment by ludofischer** [comment]
No errors with 8.2.

**Comment by alexander-akait** [comment]
@ludofischer some problems with parsing can still exists, will be great to track them, maybe in one issue

**Comment by ludofischer** [comment]
I have added [bad-parser](https://github.com/postcss/postcss-calc/labels/bad-parser) and [bad-output](https://github.com/postcss/postcss-calc/labels/bad-output) labels to track the bugs.
