### ISSUE TITLE
Postcss-calc does not calculate postcss-simple-vars values properly.

### ISSUE THREAD

**Issue by 7immy** [postcss/postcss-calc#13]
If the postcss-calc plugin is placed before postcss-simple-vars then postcss-calc doesn't calculate the values.

Perhaps you could add a notification on readme to place postcss-simple-vars before postcss-calc.

**Comment by MoOx** [comment]
This might happen with a loooot of modules in various places. This issue as already been raised and is not easy to solve. For now we consider it's up to your brain to think about this kind of issues.

**Comment by 7immy** [comment]
Cheers, I'll consult my brain next time.. Great work BTW!
