### ISSUE TITLE
Option to throw error when calc cannot be resolved

### ISSUE THREAD

**Issue by thejameskyle** [postcss/postcss-calc#19]
I would like to be able to ensure that calc can always be resolved in our styles. Would it be possible to add an option to throw if a calc cannot be resolved?

**Comment by MoOx** [comment]
This plugin is more an optimizer.
What you want is more linting. So maybe you can check stylelint (if there is a rule that can make you happy) or you can add very simple plugin to check that there is no "calc(" at all in your stylesheets. Should take 3 or 4 lines.

**Comment by thejameskyle** [comment]
I disagree that this is a linting issue. You *need* to compile the code in order to check this accurately as the way the code gets compiled directly affects if this error would be thrown or not (a trivial example being sass style variables). The alternative is linting your compiled code which doesn't make any sense.

**Comment by MoOx** [comment]
PostCSS works on an AST, so you can pipe a plugin right after this one to check what you want even before the end of the "compilation" (stringify the AST to real CSS).
Anyway, feel free to make a PR for this if you want. PR are always welcome :)

**Comment by MoOx** [comment]
FYI: this plugin does not "resolve" calc(), but "reduce them".
Example: `calc(calc(calc(1rem * 0.75) * 1.5) - 1px)` will give you `calc(1.125rem - 1px)`. Is this resolved? :)
