### ISSUE TITLE
Media Query Calc

### ISSUE THREAD

**Issue by thejameskyle** [postcss/postcss-calc#21]
Since this plugin only looks at declarations if you try using it for `@media` queries it won't work.

```js
@media (calc(100px + 200px)) {}
```

Reading the specification this should be valid

**Comment by MoOx** [comment]
The thing is, this plugin make sense when you have something to resolve (eg: after postcss-custom-properties). And if you don't (custom props don't work in mq) it does not have sense. Not sure it's relevant to handle those resolution.

**Comment by thejameskyle** [comment]
Yeah, but your are supporting an ecosystem that goes further than just the spec itself. Take postcss-simple-variables for example (which is the reason I want this) you immediately have a scenario where this makes sense.

Considering how little code it takes to support this and how I've already written it in #22 I don't see any reason you shouldn't support this case.
