### ISSUE TITLE
Does this remove something multiplied by 0?

### ISSUE THREAD

**Issue by corysimmons** [postcss/postcss-calc#23]
For instance, will `calc(10px + 100% * 0)` become `10px`?

**Comment by MoOx** [comment]
Like this `calc(10px + (100% * 0))` it will.

**Comment by corysimmons** [comment]
It doesn't take order of operations into account?

**Comment by MoOx** [comment]
Not yet. PR welcome to improve this on this repo https://github.com/MoOx/reduce-css-calc

**Comment by corysimmons** [comment]
You're implying i know how to code or do math

![](https://i.imgur.com/q95dT5G.png)

**Comment by MoOx** [comment]
You can learn thanks to search engines on the internet :)
