### ISSUE TITLE
Why is default precision 5?

### ISSUE THREAD

**Issue by corysimmons** [postcss/postcss-calc#24]
Re: https://github.com/MoOx/postcss-cssnext/issues/254

`calc(100px / 3)` = `33.33px` in IE

`calc(100px / 3)` = `33.328px` in everything else

The consequence of this is http://codepen.io/corysimmons/pen/MKQVGp?editors=1100 is a 3 column grid in everything but IE, and with cssnext turned off, it works in IE.

Is there a particular reason the default precision is 5? If not, would it be possible to tinker around with the default precision (I think 2 might be a good one to start with since IE only works with 2 spots) and consider changing it so things like Lost and cssnext work side-by-side without special configuration?

Really hope we can figure this out as I'd love to pull postcss-calc into some projects by default (my `calc` functions are super hairy and I think postcss-calc would make them much more palatable).

**Comment by MoOx** [comment]
Did you take a look at the changelog ?
You would have found this https://github.com/postcss/postcss-calc/issues/5.
You have an option to handle this.

**Comment by corysimmons** [comment]
Eh no, my bad, thanks
