### ISSUE TITLE
Further optimization

### ISSUE THREAD

**Issue by dikmax** [postcss/postcss-calc#25]
We can calculate expressions in inner parenthesis to produce simpler result

Example:

``` css
font-size: calc(14px + 6 * ((100vw - 320px) / 448)); 
```

Could be expressed as:

``` css
font-size: calc(1.3392857143vw + 9.7142857143px); 
```

or 

``` css
font-size: calc(1.34vw + 9.71px); 
```

if rounding applied.

**Comment by MoOx** [comment]
What is the point of this? Browser that will understand vw probably understand calc().
And not even sure this is correct. vw is a dynamic unit, I don't know how you end up with this weird result.
Could you add some details?

**Comment by dikmax** [comment]
Point is minimization. Maybe it's better to move this ticket to cssnano. But then I thought which project suits better I choose this one, cause it does almost same thing.

**Comment by MoOx** [comment]
Can you provide detail about the algorithm here? Or just how you end up with this result. I am not following the result your mentioned.

**Comment by dikmax** [comment]
That's quite easy, just distributive property applied.

```
  14px + 6 * ((100vw - 320px) / 448) =
= 14px + 6 * ((100/448)vw - (320/448)px)) =
= 14px + (6*100/448)vw - (6*320/448)px) =
= (6*100/448)vw + (14 - 6*320/448)px ≈ 1.3392857143vw + 9.7142857143px
```

**Comment by MoOx** [comment]
Not sure that `((100vw - 320px) / 448)` can be converted to `((100/448)vw - (320/448)px)`. That's seems too easy. Did you try the result in a browser just to see?

**Comment by dikmax** [comment]
Of course, steps in the middle are not working. I've provided them just to show idea of transformation. You have to calculate (`0.2232142857vw - 0.7142857143px`) to make it working.

**Comment by dikmax** [comment]
But when it's calculated they provide same result, i've checked.

**Comment by MoOx** [comment]
Feel free to make a PR to https://github.com/MoOx/reduce-css-calc if you have something solid (a jsfiddle with detailed step would be appreciated as well as test).

**Comment by ben-eb** [comment]
Resolved in https://github.com/postcss/postcss-calc/releases/tag/v6.0.0.

**Comment by ben-eb** [comment]
Will be resolved for version 4, see https://github.com/postcss/postcss-calc/releases/tag/v6.0.0.
