### ISSUE TITLE
Missing unit after 0

### ISSUE THREAD

**Issue by dennisfrank** [postcss/postcss-calc#28]
I use postcss-calc in [cssnano](http://cssnano.co/) and `calc(50% - 50vw + (100vw - 100vw) / 2 + 1em)` gets _optimized_ to `calc(50% - 50vw + 0 / 2 + 1em)`. Unfortunately, the unit after `0` is missing and the browser does not calculate the `calc()`statement.

`calc(50% - 50vw + 0vw / 2 + 1em)` would be the correct optimization. 

Or even better: `calc(50% - 50vw + 1em)`

`0` vs `0`+ unit.

(If you wonder why I calculate `100vw - 100vw`: it’s been generated by a [Sass mixin](http://codepen.io/df/pen/XKJOoB?editors=1100) and in most cases it makes more sense.)

**Comment by MoOx** [comment]
PR welcome to improve this behavior in https://github.com/MoOx/reduce-css-calc

**Comment by dennisfrank** [comment]
@MoOx Done: https://github.com/MoOx/reduce-css-calc/pull/11

Thanks!

**Comment by MoOx** [comment]
Fixed by https://github.com/MoOx/reduce-css-calc/commit/1ce8bd090334a790eb91785a78403af6fcd2f4d1
