### ISSUE TITLE
Remove "calc" from unresolved nested calcs

### ISSUE THREAD

**Issue by mjschlot** [postcss/postcss-calc#32]
To provide a little context and very simple example -- while keeping this short and to the point -- I am using "postcss-calc" and "postcss-advanced-variables" together (but I fully expect this issue would exist with any simply variable plugin in postcss).

Simple code to demonstrate issue:

> $a: calc(21vh + 80px * 1/3 + 5px);
$b: calc(10vw + 80px * 2/3);
.test {
	height: calc(21vh + $a + $b);
}

With PostCSS I evaluate the variables and then the calcs. Since the nested calcs contain mixed units the expressions can not easily be resolved resulting in:
> .test{
height: calc(21vh + calc(21vh + 80px * 1/3 + 5px) + calc(10vw + 80px * 2/3));
}

While Chrome understands the above expression, Edge and IE do not. What is the best approach to get postcss-calc to remove the nested calc function calls and retain the parenthesis when a nested expression can not be resolved. The result for the above would then be the following which will work in all browsers that support calc:

> .test{
height: calc(21vh + (21vh + 80px * 1/3 + 5px) + (10vw + 80px * 2/3));
}

To be clear, I am not currently concerned with the above being simplified further by postcss-calc, but simply remove the unresolved nested "calc" and leave only the outer one. 

Even though the code for this plugin and its dependencies are written very clearly and well, I am unsure the best approach to addressing the above.

**Comment by MoOx** [comment]
poke @ben-eb 
I guess we can handle that very easily in reduce-css-calc?

**Comment by ben-eb** [comment]
Yeah, something like this probably;

```js
if (stack > 1) {
  return "(" + expression + ")"
}
```

**Comment by MoOx** [comment]
@mjschlot please try by reinstalling postcss-calc (you should get reduce-css-calc@1.3.0 which handles this).

**Comment by ben-eb** [comment]
@mjschlot Also, thank you for the effort that you put into this report, helps immensely. 💯

**Comment by mjschlot** [comment]
Very nice! Thanks for the work guys, and doing it so quickly!
