### ISSUE TITLE
Mixed units of time do not reduce

### ISSUE THREAD

**Issue by ciquar** [postcss/postcss-calc#33]
A property value of `calc(1s - 50ms)` will not be reduced. Since there's functionally no difference between `950ms` and `.95s`, I would expect the latter as the output since it can be expressed in fewer characters.

This came to my attention because I'm using cssnano, which reduces time values such as `100ms` to `.1s`, or `.045s` to `45ms`. The reduction occurs prior to postcss-calc and may result in an un-reduced expression. This becomes especially problematic since some browsers will not accept `calc()` within the value of the transition property.

**Comment by MoOx** [comment]
PR welcome to https://github.com/MoOx/reduce-css-calc

**Comment by ben-eb** [comment]
Resolved in https://github.com/postcss/postcss-calc/releases/tag/v6.0.0.
