### ISSUE TITLE
I cannot use under-score before $ mark in id selector. 

### ISSUE THREAD

**Issue by mitsuru793** [postcss/postcss-calc#34]
I cannot use under-score before $ mark in id selector. Why?
I use this plugin with precss.
https://github.com/jonathantneal/precss

input
```
$result: calc(1 + 1);
div#hoge_$result {}
div#hoge-$result {}
```

output
```
div#hoge_calc(1 + 1) {}
div#hoge-2 {}
```

If I don't use calc, I can use both of under-score and hyphen.

input
```
$result: 2;
div#hoge_$result {}
div#hoge-$result {}

```

output
```
div#hoge_2 {}
div#hoge-2 {}
```

**Comment by MoOx** [comment]
postcss-calc is supposed to work only where the real calc() works. So it should not work for both case. Not sure why it's working for the first selector. Maybe because you use some non standard syntax.

**Comment by sato-sm** [comment]
@MoOx 
Thank you very much for answering.

**Comment by mitsuru793** [comment]
@MoOx 
Thank you very much for answering.
