### ISSUE TITLE
Problem on variables with `calc` on the name

### ISSUE THREAD

**Issue by celiolatorraca** [postcss/postcss-calc#35]
Hi,

First of all, thanks for this incredible lib. Saved me lots of sleeping hours.

I'm using it to reduce some `calc` and use the values into some pseudo-selectors...
Unfortunately i think i probably found a bug.

I have a variable called `$offset-calc`, and after the `postcss-calc` runs its replaced to `$offset-`...

Here is an example of a mixin i made that uses it:

```
@define-mixin elements-last-row $wrapper-selector, $selector, $row-size, $offset: 0 {
  /* last row, doesn't matter how many cells */
  $offset-calc: calc($offset + 1);
  $wrapper-selector:nth-last-child(-n + $row-size):nth-child($(row-size)n + $offset-calc), /* first element of the last row */
  $wrapper-selector:nth-last-child(-n + $row-size):nth-child($(row-size)n + $offset-calc) ~ $selector { /* all its following elements */
    @mixin-content;
  }
}
```

**Comment by MoOx** [comment]
That's a bug indeed. Please report this bug to https://github.com/MoOx/reduce-css-calc.
A PR with a failing test will be even better ;)

**Comment by ben-eb** [comment]
Resolved in https://github.com/postcss/postcss-calc/releases/tag/v6.0.0.
