### ISSUE TITLE
Nested calc not resolved (with mixed units).

### ISSUE THREAD

**Issue by lukasoppermann** [postcss/postcss-calc#37]
Hey, so I have something like this:

```css
font-size: calc(1.618 * calc(1.618 * calc(1.618 * 1em)));
```

This code is generated, from individual `calc` statements, which is why there is a calc and not only a `()` within the code.

Since safari can't handle `calc` within `calc` and starts crying, I would love this to be resolved to:

```css
font-size: calc(1.618 *(1.618 *(1.618 * 1em)));
```

Any idea why it does not work? Is this because of the mixed unit? Couldn't this be handled, so that `calc` is reduced in any case?

**Comment by MoOx** [comment]
It's actually working in [cssnext playground](http://cssnext.io/playground/) (which use this module).

<img width="853" alt="screen shot 2017-03-09 at 10 11 00" src="https://cloud.githubusercontent.com/assets/157534/23743379/b8a83c42-04b0-11e7-86c5-09ce8acf43b4.png">

**Comment by Semigradsky** [comment]
> safari can't handle `calc` within `calc`

Looks like Safari does everything right https://www.w3.org/TR/css3-values/#calc-syntax
Maybe it's old syntax?

**Comment by lukasoppermann** [comment]
This is good news. Can you maybe give me a hint how I can figure out why it is not working for me?

**Comment by MoOx** [comment]
Please provide node/npm/postcss/cssnext version and more code.

**Comment by lukasoppermann** [comment]
Hey @MoOx, thanks:

- node v7.7.2
- npm 4.1.2
- gulp-postcss 6.3.0
- postcss-calc 5.3.1
- cssnext 2.9.0

I am using gulp:

```
gulp.task('build-css', function () {
  return gulp.src([
    // npm resources
    'node_modules/minireset.css/minireset.css',
    'node_modules/open-color/open-color.css',
    'node_modules/flex-layout-attribute/css/flex-layout-attribute.css',
    'node_modules/modular-scale-css/modular-scale.css',
    // includes
    'resources/css/includes/*.css',
    // main files
    'resources/css/*.css',
    'resources/css/pages/*.css'
  ])
        // .pipe(sourcemaps.init())
        .pipe(plumber({errorHandler: notify.onError('Error: <%= error.message %>')}))
        .pipe(concat('app.css'))
        .pipe(size({
          'title': 'app.css before:',
          'pretty': true
        }))
        .pipe(postcss([
          require('postcss-import')(),
          require('postcss-will-change'),
          require('postcss-discard-comments'),
          require('cssnano')({
            // autoprefixer: false,
            discardComments: {
              removeAll: true
            }
            // zindex: false
          }),
          require('postcss-cssnext')({
            browsers: ['last 2 versions']
          }),
          require('postcss-color-function'),
          // require('postcss-calc-function').default(),
          require('postcss-calc')(),
          require('postcss-reporter')({
            plugins: [
              'postcss-color-function'
            ]
          })
        ]))
        .pipe(size({
          'title': 'app.css after:',
          'pretty': true
        }))
        .pipe(size({
          'title': 'app.css gzip:',
          'pretty': true,
          'gzip': true
        }))
        // .pipe(sourcemaps.write('/'))
        .pipe(gulp.dest('public/build/css'))
})
```

The css comes from `modular-scale.css` in the for of variables like those:

```
  --ms0   : var(--ms-base, 1em);
  --ms1   : calc(var(--ms-ratio, var(--golden)) * var(--ms0));
  --ms2   : calc(var(--ms-ratio, var(--golden)) * var(--ms1));
```

I hope this helps?

**Comment by lukasoppermann** [comment]
Okay, move it above css next fixed it, I think.

**Comment by MoOx** [comment]
FYI, postcss-calc is included in cssnext. Same for postcss-color-function. Also you should probably use cssnano at the end of your stack...

**Comment by lukasoppermann** [comment]
@MoOx thanks, I did not know this.
