### ISSUE TITLE
Cannot wrap inner value in negative

### ISSUE THREAD

**Issue by TheSisb** [postcss/postcss-calc#40]
Not sure how to title this issue correctly, but the issue is if you do something like
```css
left: calc(-(10px + (10px / 2)));
```

postcss-calc gets mad and says:
```
-(10px + (10px / 2))
-^
Expecting 'SUB', 'PREFIX', 'NUMBER', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'LPAREN'
```

But I think this should work... and it did in older versions.

[edit] Added a test to verify, you can see the error if you attempt this test: https://github.com/TheSisb/postcss-calc/commit/375688acbf1198f3b9a01a67fb5160a97022b491

**Comment by Kovensky** [comment]
It seems `postcss-calc` no longer supports parenthesized expressions -- any nested parenthesis needs to be itself `calc()`.

**Comment by lkraav** [comment]
What if you don't know the incoming unit, in the case of a mixin?

**Comment by andyjansson** [comment]
>```
>left: calc(-(10px + (10px / 2)));
>```

This isn't valid CSS. Open up a browser's inspector and it will tell you that it's an invalid property value. 

The correct way of doing it is either of the following: 

```
left: calc(0px - (10px + (10px / 2))); 
```

```
left: calc((10px + (10px / 2)) * -1);
```

**Comment by andyjansson** [comment]
Closing this since it has already been answered.
