### ISSUE TITLE
Ignoring proper order of operations

### ISSUE THREAD

**Issue by uvuwolverine** [postcss/postcss-calc#41]
Found an issue where it's removing the inner parenthesis needed for correct ordering of calculations. For example, the following calculates the width minus the scroll bar(which some browsers include in the vw while others don't:
`width: calc(100vw - (100vw - 100%))`
That should return the width of the window minus the scroll bar, but the inner parenthesis are removed and it returns:
`width: calc(0vw - 100%)`

**Comment by andyjansson** [comment]
I'd like to point you to the following issue: https://github.com/MoOx/reduce-css-calc/issues/28 

It's not so much that it's ignoring the order of operations as it is an incorrect optimisation.

**Comment by Semigradsky** [comment]
Should be fixed. Just reinstall `reduce-css-calc` dependency.
