### ISSUE TITLE
Cannot use constant values

### ISSUE THREAD

**Issue by darrellhanley** [postcss/postcss-calc#42]
iOS 11 Safari added support for constant declarations for safe areas, eg `constant(safe-area-inset-bottom)` which returns a dynamic value for the amount of margin or padding needed to avoid unsafe areas. Currently, when a constant value is used in calc, it causes postcss to fail generating the following error:

```
Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'PREFIX']
message: 'Parse error on line 1:\nconstant(safe-area-i\n^\nExpecting \'SUB\', \'LPAREN\', \'NESTED_CALC\', \'NUMBER\', \'CSS_VAR\', \'LENGTH\', \'ANGLE\', \'TIME\', \'FREQ\', \'RES\', \'EMS\', \'EXS\', \'CHS\', \'REMS\', \'VHS\', \'VWS\', \'VMINS\', \'VMAXS\', \'PERCENTAGE\', got \'PREFIX\'',
showStack: false,
showProperties: true,
plugin: 'gulp-postcss',
 __safety: { toString: [Function: bound ] } }
```

**Comment by darrellhanley** [comment]
Seems to be an issue upstream, offhand from [reduce-css-calc](https://github.com/MoOx/reduce-css-calc)

**Comment by Semigradsky** [comment]
https://github.com/MoOx/reduce-css-calc/issues/34

**Comment by zoosky** [comment]
Using Framework7 affected by this bug. See https://github.com/framework7io/framework7/issues/2539

**Comment by andyjansson** [comment]
Should be fixed in latest release.
