### ISSUE TITLE
Support or skip quirk unit？

### ISSUE THREAD

**Issue by LucasIcarus** [postcss/postcss-calc#45]
I'm using cssnano with postcss-calc in wechat-mini-program development.

Wechat introduces a unique unit called 'rpx' represent 1/750 of the device width.

When using cssnano@4.0.0.rc with postcss-calc, an error

```
Error: Lexical error on line 1. Unrecognized text.
  100% - 50rpx
  -------^
```
returned..

**Comment by LucasIcarus** [comment]
With

```
([0-9]+("."[0-9]*)?|"."[0-9]+)rem\b    return 'REMS';
([0-9]+("."[0-9]*)?|"."[0-9]+)rpx\b    return 'RPXS';
```

```
  	| REMS { $$ = { type: 'RemValue', value: parseFloat($1), unit: 'rem' }; }
  	| RPXS { $$ = { type: 'RpxValue', value: parseFloat($1), unit: 'rpx' }; }
```

simple changes in parser.jison, the error above resolved.

In view of rpx is not a standard, any guides about this?

**Comment by Semigradsky** [comment]
@LucasIcarus How about not use non standard `rpx` and use `vw` instead?

**Comment by YikaJ** [comment]
+1.
in that situation, pass the non standard is the best way to do it.

**Comment by LucasIcarus** [comment]
For now, we create a simple loader to transform the unit and as far as possible to avoid using it.

Thanks you guys.
