### ISSUE TITLE
Add precision option

### ISSUE THREAD

**Issue by 7studio** [postcss/postcss-calc#5]
For the moment, the plugin uses `5` as a magic number to define the number of digits of precision.
I didn't find any line in the documentation which explains this choice but in some cases it doesn't make sense : [Em values are rounded or truncated at 2 decimals](https://connect.microsoft.com/IE/Feedback/Details/1003699).
I'm sure that if we search in your experience, we will find many problematic cases with the use of the decimals.

I'm trying an experience with this mathematical expression **(100% \* 1 / 3)** to look at the other tools:

| Tool | Result | Precision |
| :-- | :-- | --: |
| Stylus | `33.333333333333336%` | 15 |
| Sass | `33.33333%` | 5 |
| Less.js | `33.33333333%` | 8 |
| cssnext | `33.33333%` | 5 |
| reworkcss | `33.33333333333333%` | 14 |

I'm not surprised by this huge difference between tools, and obviously none of them clearly explains its choice about the precision.
For that, it could be interesting to allow users to define their own precision with an option (e.g.: `precision`) like Sass does.

Plus, if we decide to go ahead and that we take note of this article [Using decimal percentage values in responsive design](http://nimbupani.com/using-decimal-percentage-values-in-responsive-design.html) by Divya Manian, we could add a second option (e.g.: `preserve`) like the plugin `postcss­-custom-properties` to have an acceptable result (current working) but also it would allow browsers to do their own optimizations for accuracy with the calc() function.

Exemple with the options `precision: 3` and `preserve: true`:

``` css
h1 {
  width: calc(1/6 * 100%)
}
```

you will get:

``` css
h1 {
  width: 16.667%;
  width: calc(1/6 * 100%)
}
```

I don't think it would be important to preserve `calc()` if the result is an integer (e.g.: `calc(10px * 2)`) but the behaviour could be disturbing.

**Comment by corysimmons** [comment]
Precision 2 makes `100 / 3` work with IE. I can use the precision option though. no problem
