### ISSUE TITLE
Breaks CSS variables that include "calc" in their name

### ISSUE THREAD

**Issue by JayCanuck** [postcss/postcss-calc#50]
It appears that `postcss-calc`is incorrectly matching the word `calc` from within a css variable name.

The source:
```css
transform: translateY(calc(-100% - var(--tooltip-calculated-offset)))
```

Is being transformed into
```css
transform: translateY(calc(-100% - var(-ulated-offset)))
```

I suspect a more complex [calc match regex](https://github.com/postcss/postcss-calc/blob/master/src/lib/transform.js#L4) would be needed to exclude variables that just contain the word fragment "calc".

**Comment by andyjansson** [comment]
Should be fixed in latest release.
