### ISSUE TITLE
remove space in `var` and default value

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-calc#57]
/cc @andyjansson Should postcss-calc remove space in `var` (between name variable and default value) or we should do this in `cssnano`?

Input:
```css
calc(var(--width, 100px) + 1px)
```

Output:
```css
calc(var(--width, 100px) + 1px)
```

Expected:
```css
calc(var(--width,100px) + 1px)
```

**Comment by jonathantneal** [comment]
My two cents are to keep things limited to calc.

**Comment by andyjansson** [comment]
Yeah, out of scope for this plugin.
