### ISSUE TITLE
Adding a .eslintrc

### ISSUE THREAD

**Issue by MartijnCuppens** [postcss/postcss-calc#59]
I think we'll need an `.eslintrc` file to ensure the quality and consistency of the javascript code. For example I noticed the mixed usage of single and double quotes in the javascript files.

**Comment by andyjansson** [comment]
We do have eslint. It's registered in package.json instead of a separate file.

**Comment by jonathantneal** [comment]
@MartijnCuppens, see https://github.com/postcss/postcss-calc/blob/master/package.json#L26-L29

**Comment by MartijnCuppens** [comment]
Ok, thanks guys! Love the response time ❤️
