### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by leimonio** [postcss/postcss-calc#65]
After cloning project locally, I'm not able to install the dependencies with `yarn install`.

Generated error:
`error Couldn't find package "@babel/cli" on the "npm" registry.`

Seems like `del-cli` has a dependency on `registry-auth-token` which requires an auth token to complete npm related actions.

**Comment by andyjansson** [comment]
Sounds like an issue on your end. `@babel/cli` is very much [on the npm registry](https://www.npmjs.com/package/@babel/cli). As for `del-cli`, it's a dev dependency, and is not required to use the package. As for requiring an auth token, no, it does not.
