### ISSUE TITLE
Remove units in same-unit-division

### ISSUE THREAD

**Issue by SpikeShape** [postcss/postcss-calc#68]
I stumbled across the problem that units are still present although I am dividing by a value with the same unit.

Example:
```
font-size: calc(10px/16px) // should give 0.625 but gives 0.625px
```

Is there a way to work around this issue or is there an option to make it work?

Thanks in advance! I have been using your plugin for several years and it has helped a ton!

**Comment by andyjansson** [comment]
Do you have the latest version? What you're doing isn't valid. 

https://github.com/postcss/postcss-calc/blob/master/src/__tests__/index.js#L562
