### ISSUE TITLE
[feat] Hope to support new units 'rpx'

### ISSUE THREAD

**Issue by bigmeow** [postcss/postcss-calc#76]
In China, the Wechat applet is very popular. It defines a responsive unit,'rpx'

code:
```css
width: calc(100% - 10rpx);
```
I hope the above code will work properly.

Try to modify the following code to make it work
https://github.com/postcss/postcss-calc/blob/185f0fb0618302f2a27d71ee4150341d93e23e5a/src/parser.jison#L17

``` js
//update after
([0-9]+("."[0-9]+)?|"."[0-9]+)r?px\b              return 'LENGTH';
```

Is this proposal acceptable to you?

**Comment by bigmeow** [comment]
Or users can customize unit validation

**Comment by evilebottnawi** [comment]
Can you provide link on spec or docs

**Comment by evilebottnawi** [comment]
And what is unit means

**Comment by evilebottnawi** [comment]
rpx !== px and it is non standard, so we just relax parser to avoid throw error on unknown unit
