### ISSUE TITLE
Support exponential math operations

### ISSUE THREAD

**Issue by teddybradford** [postcss/postcss-calc#8]
Has there been any discussion about including support for more advanced math operations such as exponents? For example: `calc(2 ^ 3)` or `calc(var(--x) ^ 3)`.

Exponents are extremely useful for setting up things like modular scales. However, right now you have to multiply long strings of variables together to achieve the same result, e.g., `calc(2 * var(--y) * var(--y) * var(--y) * var(--y))`. As you can see, it can get quite tedious. Ideally I would prefer to write something like `calc(2 * var(--y) ^ 4)` instead.

What are your thoughts on implementing support for exponents?

**Comment by MoOx** [comment]
The idea of this plugin is just to reduce valid existing CSS and I didn't see that in the spec last time I checked. Is there any stuff about that now ?

**Comment by teddybradford** [comment]
I'm not sure. I was simply curious about the scope of this project and whether or not it might be extended to support other math operations. Perhaps in the future a `postcss-calc-extended` fork that goes beyond the scope of the W3C spec may be considered.

**Comment by MoOx** [comment]
FYI this plugin is nothing more that a wrapper of https://github.com/MoOx/reduce-css-calc.
We may add this as a disabled option by default.

**Comment by andyjansson** [comment]
This plugin will be kept in line with the W3C specification.
