### ISSUE TITLE
 JisonLexerError: Lexical error on line 1: Unrecognized text - Erroneous area

### ISSUE THREAD

**Issue by seth100** [postcss/postcss-calc#99]
Hi,

I am using `nuxt.js` and the [RFS](https://github.com/twbs/rfs) unit resizing engine.
After updating to the latest version `v9.0.1` I have the following errors happening for every occorrence of `@include font-size(...);` mixin (see https://github.com/twbs/rfs#input).

E.g. 

```scss
@include font-size(4rem);
```

generates:

```css
font-size: calc(1.525rem + 3.3vw);
```

but in my case, after postcss, it is:

```
1.525rem3.3vw
```

and the complete errors is:

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):                                                                                                                   friendly-errors 20:44:54
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 1.525rem3.3vw
^...^
```

Could you please fix it?
Thanks

**Comment by jasminexie** [comment]
I don't think this is a postcss-calc problem. I've tested `font-size: calc(1.525rem + 3.3vw);` with postcss and postcss-calc (latest versions) and the expression has not been reduced. The [tests](https://github.com/postcss/postcss-calc/blob/master/src/__tests__/index.js) in this project also cover similar cases.

**Comment by seth100** [comment]
Great, thank you for the info
